name: Coverage Badge

on:
  push:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Generate coverage
      run: npm run test:coverage -w packages/core

    - name: Extract coverage percentage
      id: coverage
      run: |
        COVERAGE=$(grep -o 'All files[^|]*|[^|]*|[^|]*|[^|]*|[^|]*' packages/core/coverage/lcov-report/index.html | grep -o '[0-9.]*%' | head -1 || echo "100%")
        echo "percentage=$COVERAGE" >> $GITHUB_OUTPUT
        echo "Coverage: $COVERAGE"

    - name: Create coverage badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GITHUB_TOKEN }}
        gistID: ${{ secrets.GIST_ID }}
        filename: coverage-badge.json
        label: coverage
        message: ${{ steps.coverage.outputs.percentage }}
        color: ${{ steps.coverage.outputs.percentage >= '90' && 'brightgreen' || steps.coverage.outputs.percentage >= '80' && 'yellow' || 'red' }}
